// @ts-check

/**
 * Turns the naming decision into one command.
 *
 * The public name is not a marketing detail here: the working title `agent-crm` is
 * also the npm package name, the bin key, two binary filenames, the MCP server keys
 * in four harness configs, the plugin name that namespaces every skill, the MCP
 * registry namespace, the SQLite filename and an environment-variable prefix. A
 * rename touched by hand across those surfaces is a rename that half-lands.
 *
 * `docs/RENAME_SURFACE.md` is the inventory this script executes. Both are grouped by
 * blast radius, because the groups behave differently:
 *
 *   cosmetic        prose. Wrong-but-harmless until someone reads it.
 *   public-surface  site/brand.json. Everything in site/ and docs/marketing/ reads
 *                   these tokens, so the whole public surface is one edit.
 *   distribution    plugin name, npm scope, registry namespace. Unrenameable once
 *                   published — a published skill namespace cannot be taken back.
 *   code            package.json, binary filenames, MCP server keys, database
 *                   filename, env prefix. Breaks existing checkouts and any config
 *                   a user has already installed.
 *
 * Discipline, matching the module factory and the MCP scaffolding tools (ADR: code
 * generation is dry-run until an explicit apply): nothing is written without
 * `--apply`, `--apply` refuses to run on a dirty tree, and the run is deterministic —
 * same tree and same arguments produce byte-identical output.
 *
 * It never contacts the network and never registers anything. Registering the npm
 * scope, the GitHub org, the domain and the directory listings are human actions;
 * the run ends by printing them.
 *
 * Run: node scripts/brand-set.js <name> [--slug <slug>] [--apply]
 */

import { readFileSync, writeFileSync, readdirSync, statSync, existsSync, renameSync } from 'node:fs';
import { spawnSync } from 'node:child_process';
import { join, relative } from 'node:path';

const root = process.cwd();

/**
 * The working title, in every casing it wears in the tree. These are historical
 * constants: they are what the repository said before any rename ran.
 */
const WORKING_TITLE = { slug: 'agent-crm', display: 'Agent CRM' };

/**
 * Directories that are not source: dependencies, history, build output, local data.
 * `site/dist` is generated by `npm run site:build` and regenerated after a rename.
 */
const SKIP_DIRECTORIES = new Set(['node_modules', '.git', 'dist', 'data', 'coverage', '.tmp']);

/**
 * Files left alone on purpose, each for one of two reasons.
 *
 * A document whose *subject* is the naming decision quotes the old name as evidence:
 * rewriting it turns "why agent-crm is unsuitable" into a sentence that argues against
 * the name it just chose. A historical record — an ADR, a merged ExecPlan — states what
 * was true when it was written, and retroactively editing it is falsification, not a
 * rename. Both are reported rather than silently skipped.
 */
const EXCLUDED = [
  {
    path: 'scripts/brand-set.js',
    why: 'this script. WORKING_TITLE is a historical constant — rewriting it erases the mapping a second run needs',
  },
  { path: 'docs/RENAME_SURFACE.md', why: 'the inventory of this rename; it quotes the old name throughout' },
  { path: 'docs/strategy/BRAND_REQUIREMENTS.md', why: 'argues why the working title is unsuitable; the quotes are the evidence' },
  { path: 'docs/marketing/NAME_VERIFICATION.md', why: 'the naming research, including the candidates that lost' },
  { path: 'DECISIONS.md', why: 'ADR history — a record of what was true when it was written' },
  { path: 'docs/plans/', why: 'merged ExecPlans — historical records of completed work' },
];

/**
 * Occurrences that are correct today and must not move until a human moves something
 * outside this repository first. A GitHub URL resolves to a repository that exists
 * under its current name; the MCP registry namespace `io.github.<owner>/<repo>` is
 * ownership-checked against that same repository. Rewriting either ahead of the
 * GitHub rename produces a manifest that points at nothing.
 */
const DEFERRED = [
  {
    what: 'GitHub repository URLs (github.com/<owner>/<repo>)',
    why: 'they resolve today; they change when a human renames the GitHub repository, not before',
  },
  {
    what: 'server.json name — the io.github.<owner>/<repo> MCP registry namespace',
    why: 'the registry verifies it against the GitHub repository, so it follows that rename',
  },
  {
    what: 'docs/strategy/AGENT_CRM_CLOUD.md and the AGENT_CRM_CLOUD.md references in nine documents',
    why: 'a document filename, cross-referenced from other documents; renaming files is a separate reviewed change',
  },
];

/** Marketplace names reserved by Anthropic. Kept in step with scripts/distribution-check.js. */
const RESERVED = new Set([
  'claude-code-marketplace', 'claude-code-plugins', 'claude-plugins-official',
  'claude-plugins-community', 'claude-community', 'anthropic-marketplace',
  'anthropic-plugins', 'agent-skills', 'anthropic-agent-skills',
  'knowledge-work-plugins', 'life-sciences', 'claude-for-legal',
  'claude-for-financial-services', 'financial-services-plugins',
  'first-party-plugins', 'healthcare',
]);

const SLUG_PATTERN = /^[a-z][a-z0-9]*(?:-[a-z0-9]+)*$/;

// ---------------------------------------------------------------- arguments

const argv = process.argv.slice(2);
let requestedName = null;
let requestedSlug = null;
let apply = false;

for (let index = 0; index < argv.length; index += 1) {
  const arg = argv[index];
  if (arg === '--apply') apply = true;
  else if (arg === '--slug') {
    requestedSlug = argv[index + 1] ?? '';
    index += 1;
  } else if (arg.startsWith('--slug=')) requestedSlug = arg.slice('--slug='.length);
  else if (arg === '--help' || arg === '-h') usage(0);
  else if (arg.startsWith('-')) refuse(`unknown option ${arg}`);
  else if (requestedName === null) requestedName = arg;
  else refuse(`unexpected argument "${arg}" — the name is a single kebab-case token`);
}

if (requestedName === null) usage(1);

const name = requestedName;
const slug = requestedSlug ?? name;

if (!SLUG_PATTERN.test(name) || name.length < 2 || name.length > 32) {
  const suggestion = name
    .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
  refuse(
    `"${name}" is not a plausible identifier. It becomes an npm package name, a bin key, a `
    + 'filename and a plugin namespace, so it must be kebab-case (lowercase letters and digits, '
    + 'single hyphens between them, starting with a letter) and 2-32 characters.'
    + (SLUG_PATTERN.test(suggestion) && suggestion.length >= 2 && suggestion.length <= 32
      ? ` Did you mean "${suggestion}"? The display name is derived from it.`
      : ''),
  );
}
if (!SLUG_PATTERN.test(slug) || slug.length < 2 || slug.length > 32) {
  refuse(`--slug "${slug}" is not kebab-case, 2-32 characters.`);
}
if (RESERVED.has(name) || RESERVED.has(slug) || RESERVED.has(`${slug}-marketplace`)) {
  refuse(
    `"${slug}" collides with a marketplace name reserved by Anthropic. A plugin or marketplace `
    + 'published under it will not load (see scripts/distribution-check.js).',
  );
}
if (/official|anthropic|claude/i.test(name) || /official|anthropic|claude/i.test(slug)) {
  refuse(`"${slug}" implies an official or first-party source. Distribution manifests block that name.`);
}
if (slug === WORKING_TITLE.slug) {
  refuse(
    `"${slug}" is the working title. docs/strategy/BRAND_REQUIREMENTS.md is the argument for why `
    + 'it cannot be the public name.',
  );
}

const words = slug.split('-');
const target = {
  slug,
  display: words.map(capitalise).join(' '),
  pascal: words.map(capitalise).join(''),
  snake: slug.replace(/-/g, '_'),
  envPrefix: slug.toUpperCase().replace(/-/g, '_'),
};

// ---------------------------------------------------------------- brand tokens

const brandPath = join(root, 'site/brand.json');
if (!existsSync(brandPath)) {
  refuse('site/brand.json not found. Run this from the repository root.');
}
const brandSource = readFileSync(brandPath, 'utf8');
/** @type {any} */
const brand = JSON.parse(brandSource);

/**
 * Old tokens are the working title plus whatever brand.json currently records, so a
 * second run — the trademark screen came back badly, the name changes again — still
 * finds the surfaces the first run renamed.
 * @type {{slug: string, display: string}[]}
 */
const previous = [];
for (const candidate of [{ slug: String(brand.name?.slug ?? ''), display: String(brand.name?.value ?? '') }, WORKING_TITLE]) {
  if (!SLUG_PATTERN.test(candidate.slug) || candidate.slug === target.slug) continue;
  if (previous.some((entry) => entry.slug === candidate.slug)) continue;
  previous.push(candidate);
}
if (previous.length === 0) {
  console.log(`brand-set: nothing to rename — the tree already uses "${target.slug}".`);
  process.exit(0);
}

/** @type {{from: string, to: string, pattern: RegExp, note: string}[]} */
const rules = [];
/** @type {string[]} */
const ruleNotes = [];
for (const old of previous) {
  const oldWords = old.slug.split('-');
  const oldPascal = oldWords.map(capitalise).join('');
  const oldEnv = old.slug.toUpperCase().replace(/-/g, '_');
  const oldSnake = old.slug.replace(/-/g, '_');

  // The env prefix, except AGENT_CRM_CLOUD, which is a document filename.
  addRule(`${oldEnv}_`, `${target.envPrefix}_`, new RegExp(`${escape(oldEnv)}_(?!CLOUD)`, 'g'), 'environment-variable prefix');
  // Identifiers before prose. A one-word old name spells its display form and its
  // identifier form the same way ("Accordo"), and no amount of text matching can tell
  // `createAccordoApp` from a sentence. Renaming it to a multi-word name has to pick
  // one: picking the identifier form leaves prose reading "LeadForge", which a human
  // fixes; picking the prose form emits `createLead ForgeApp`, which does not parse.
  addRule(oldPascal, target.pascal, new RegExp(escape(oldPascal), 'g'), 'exported identifiers');
  addRule(old.display, target.display, new RegExp(escape(old.display), 'g'), 'display name in prose');
  if (old.display === oldPascal && target.display !== target.pascal) {
    ruleNotes.push(
      `"${oldPascal}" is both the display name and the identifier stem, and "${target.display}" is two words. `
      + `Every occurrence becomes "${target.pascal}" so the code still parses; re-read the prose afterwards.`,
    );
  }
  // The slug, except where it is part of a GitHub URL or the registry namespace.
  addRule(
    old.slug,
    target.slug,
    new RegExp(`(?<!github\\.com/[\\w.-]{1,64}/)(?<!io\\.github\\.[\\w.-]{1,64}/)${escape(old.slug)}`, 'g'),
    'package name, bin key, filenames, plugin namespace, database file',
  );
  addRule(oldSnake, target.snake, new RegExp(escape(oldSnake), 'g'), 'MCP server key in TOML and Codex configs');
}

/**
 * @param {string} from
 * @param {string} to
 * @param {RegExp} pattern
 * @param {string} note
 */
function addRule(from, to, pattern, note) {
  if (from === to) return;
  if (rules.some((rule) => rule.from === from)) return;
  rules.push({ from, to, pattern, note });
}

// ---------------------------------------------------------------- surfaces

/** Blast-radius groups, most dangerous last so the report ends on what breaks. */
const GROUPS = [
  { id: 'cosmetic', label: 'cosmetic — prose, no consumer breaks' },
  { id: 'public-surface', label: 'public-surface — site and marketing, token-driven, one edit' },
  { id: 'distribution', label: 'distribution — unrenameable once published' },
  { id: 'code', label: 'code — breaks existing checkouts and installed configs' },
];

const DISTRIBUTION_FILES = new Set([
  '.claude-plugin/plugin.json',
  '.claude-plugin/marketplace.json',
  '.codex-plugin/plugin.json',
  '.agents/plugins/marketplace.json',
  'gemini-extension.json',
  'server.json',
]);

/**
 * @param {string} path repository-relative, forward slashes
 * @returns {string} group id
 */
function groupOf(path) {
  if (path === 'site/brand.json') return 'public-surface';
  if (DISTRIBUTION_FILES.has(path)) return 'distribution';
  if (/^\.(claude|agents)\/skills\/[^/]+\/SKILL\.md$/.test(path)) return 'distribution';
  if (path.endsWith('.md')) return 'cosmetic';
  if (path === 'apps/admin/public/index.html') return 'cosmetic';
  return 'code';
}

/** Binaries whose filename carries the name. Their contents are covered by the text rules. */
const renames = [];
for (const suffix of ['', '-inspect']) {
  for (const old of previous) {
    const from = `packages/cli/bin/${old.slug}${suffix}.js`;
    if (!existsSync(join(root, from))) continue;
    renames.push({ from, to: `packages/cli/bin/${target.slug}${suffix}.js` });
  }
}

/** @type {{path: string, group: string, hits: {from: string, to: string, count: number}[]}[]} */
const edits = [];
for (const path of walk(root)) {
  if (isExcluded(path)) continue;
  let source;
  try {
    source = readFileSync(join(root, path), 'utf8');
  } catch {
    continue;
  }
  if (source.includes('\u0000')) continue;

  const hits = [];
  for (const rule of rules) {
    const count = (source.match(rule.pattern) ?? []).length;
    if (count > 0) hits.push({ from: rule.from, to: rule.to, count });
  }
  if (hits.length > 0) edits.push({ path, group: groupOf(path), hits });
}
edits.sort((a, b) => (a.path < b.path ? -1 : 1));

// ---------------------------------------------------------------- report

const mode = apply ? 'apply' : 'dry run';
console.log(`brand-set: ${mode}`);
console.log('');
const fromWidth = Math.max(...rules.map((rule) => rule.from.length));
const toWidth = Math.max(...rules.map((rule) => rule.to.length));
for (const rule of rules) {
  console.log(`  ${rule.from.padEnd(fromWidth)}  →  ${rule.to.padEnd(toWidth)}   ${rule.note}`);
}
console.log('');
console.log(`  npm scope   @${target.slug}     create command  npm create ${target.slug}`);
console.log('');
for (const note of ruleNotes) console.log(`  note: ${note}\n`);

let totalOccurrences = 0;
for (const group of GROUPS) {
  const members = edits.filter((edit) => edit.group === group.id);
  const occurrences = members.reduce((sum, edit) => sum + edit.hits.reduce((n, hit) => n + hit.count, 0), 0);
  totalOccurrences += occurrences;
  console.log(`── ${group.label}`);
  console.log(`   ${members.length} file(s), ${occurrences} occurrence(s)`);
  for (const edit of members) {
    console.log(`   ${edit.path}`);
    for (const hit of edit.hits) console.log(`       ${String(hit.count).padStart(3)} ×  ${hit.from}  →  ${hit.to}`);
  }
  console.log('');
}

console.log('── code — file renames');
if (renames.length === 0) console.log('   none');
for (const rename of renames) console.log(`   ${rename.from}  →  ${rename.to}`);
console.log('');

console.log('── public-surface — site/brand.json token edits');
for (const line of brandEdits(brandSource).description) console.log(`   ${line}`);
console.log('');

console.log('── deferred — correct today, and not this script\'s to move');
for (const item of DEFERRED) console.log(`   ${item.what}\n       ${item.why}`);
console.log('');

console.log('── excluded — left alone on purpose');
for (const item of EXCLUDED) console.log(`   ${item.path}\n       ${item.why}`);
console.log('');

// ---------------------------------------------------------------- apply

if (apply) {
  const status = spawnSync('git', ['status', '--porcelain'], { cwd: root, encoding: 'utf8' });
  if (status.error || status.status !== 0) {
    refuse(`could not read git status: ${status.error?.message ?? status.stderr?.trim() ?? 'unknown error'}`);
  }
  if (status.stdout.trim() !== '') {
    refuse(
      'the working tree is dirty. This rewrites '
      + `${edits.length} files and renames ${renames.length}; a rename you cannot revert with one `
      + '`git checkout .` is a rename you should not start. Commit or stash first.',
    );
  }

  for (const edit of edits) {
    const full = join(root, edit.path);
    let source = readFileSync(full, 'utf8');
    for (const rule of rules) source = source.replace(rule.pattern, rule.to);
    writeFileSync(full, source);
  }

  const brandResult = brandEdits(readFileSync(brandPath, 'utf8'));
  writeFileSync(brandPath, brandResult.text);
  const check = JSON.parse(readFileSync(brandPath, 'utf8'));
  if (check.name.value !== target.display || check.name.slug !== target.slug || check.name.status !== 'chosen') {
    refuse('site/brand.json did not take the new tokens. Revert with `git checkout site/brand.json` and report this.');
  }

  for (const rename of renames) {
    const moved = spawnSync('git', ['mv', rename.from, rename.to], { cwd: root, encoding: 'utf8' });
    if (moved.status !== 0) renameSync(join(root, rename.from), join(root, rename.to));
  }

  console.log(`written: ${edits.length} file(s), ${renames.length} rename(s), site/brand.json.`);
  console.log('');
} else {
  console.log(`dry run: ${edits.length} file(s) and ${totalOccurrences} occurrence(s) would change, plus ${renames.length} rename(s) and site/brand.json.`);
  console.log('Nothing was written. Re-run with --apply.');
  console.log('');
}

// ---------------------------------------------------------------- what a human must do

console.log('── still to do, by a human — no agent may do any of these');
for (const line of [
  `npm — register "${target.slug}", "create-${target.slug}" and the "@${target.slug}" scope. Namespaces are`,
  '      first-come and unrenameable; publishing under a squatted name later is not an option.',
  `GitHub — create or rename the org and repository to "${target.slug}", then update the repository URLs`,
  `      (site/brand.json repository.value and the plugin manifests) and server.json's io.github.<owner>/${target.slug}.`,
  `domain — register the domain and move site/brand.json domain.status to "registered". Until then the`,
  '      absolute URLs the site builds point at something nobody owns.',
  'trademark — run the screen (classes 9 and 42) before anything is published. A live word-mark found after',
  '      the npm scope and the plugin namespace are public is a rename that cannot be undone.',
  'directories — npm publish, the MCP registry, the Claude plugin marketplace and any other listing are',
  '      submissions (docs/strategy/MASTER_PLAN.md §10.4). This script contacts no network and submits nothing.',
  'brand.json — rewrite name.note with the rationale for this name. The script does not invent a rationale.',
  `local — your SQLite file is still ${previous.map((old) => `data/${old.slug}.sqlite`).join(' or ')} and is gitignored: rename it or set`,
  '      CRM_DB_PATH. Any .mcp.json already installed in a user\'s project still names the old server key.',
  'licence — confirm MIT (docs/strategy/MASTER_PLAN.md §10.2) and move site/brand.json license.status to',
  '      "confirmed". Three distribution manifests already assert a licence to a marketplace.',
  'verify — npm run verify, then npm run gtm:check. The bin key, the server keys and the plugin namespace',
  '      all moved; nothing here is done until both pass. Expect distribution-check to fail on two counts',
  '      it holds back until a name exists: the bundled skills are still repo-bound, and the licence is',
  '      unconfirmed. Choosing the name is what makes those blocking, and neither is fixed by renaming.',
]) console.log(`   ${line}`);

// ---------------------------------------------------------------- helpers

/**
 * Rewrites the three name tokens plus the two npm tokens derived from them, in place,
 * so brand.json keeps its comments, its notes and its byte layout everywhere else.
 * @param {string} text
 * @returns {{text: string, description: string[]}}
 */
function brandEdits(text) {
  const description = [];
  let output = text;

  /**
   * @param {string} block
   * @param {string} key
   * @param {string} value
   */
  function setString(block, key, value) {
    const pattern = new RegExp(`("${block}":\\s*\\{[^{}]*?"${key}":\\s*)"(?:[^"\\\\]|\\\\.)*"`);
    const match = output.match(pattern);
    if (!match) {
      description.push(`${block}.${key}: not found — brand.json has moved; this token is unchanged`);
      return;
    }
    const current = JSON.parse(match[0].slice(match[1].length));
    output = output.replace(pattern, `$1${JSON.stringify(value)}`);
    description.push(`${block}.${key}: ${JSON.stringify(current)}  →  ${JSON.stringify(value)}`);
  }

  setString('name', 'status', 'chosen');
  setString('name', 'value', target.display);
  setString('name', 'slug', target.slug);
  setString('npm', 'scope', `@${target.slug}`);
  setString('npm', 'createCommand', `npm create ${target.slug}`);

  return { text: output, description };
}

/**
 * @param {string} directory
 * @returns {string[]} repository-relative paths
 */
function walk(directory) {
  const results = [];
  for (const entry of readdirSync(directory).sort()) {
    if (SKIP_DIRECTORIES.has(entry)) continue;
    const full = join(directory, entry);
    if (statSync(full).isDirectory()) results.push(...walk(full));
    else results.push(relative(root, full).split('\\').join('/'));
  }
  return results;
}

/** @param {string} path */
function isExcluded(path) {
  return EXCLUDED.some((item) => (item.path.endsWith('/') ? path.startsWith(item.path) : path === item.path));
}

/** @param {string} word */
function capitalise(word) {
  return word.charAt(0).toUpperCase() + word.slice(1);
}

/** @param {string} literal */
function escape(literal) {
  return literal.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

/** @param {string} message */
function refuse(message) {
  console.error(`brand-set refused: ${message}`);
  process.exit(1);
}

/** @param {number} code */
function usage(code) {
  const write = code === 0 ? console.log : console.error;
  write('Usage: node scripts/brand-set.js <name> [--slug <slug>] [--apply]');
  write('');
  write('  <name>          the public name, kebab-case, 2-32 characters');
  write('  --slug <slug>   package/namespace slug, when it differs from the name');
  write('  --apply         write the changes. Without it nothing is written.');
  write('');
  write('The inventory this executes is docs/RENAME_SURFACE.md.');
  process.exit(code);
}
